{
 ### Environment Parameters
#  debug: true,
  debug: false,
  mode: train,
  cuda: true,
  pin_memory: true,
  wandb: true,
  worker: 8,
  log_interval: 9999,
  save_interval: 1,
  saved_model_directory: 'model_ckpts',
  train_fold: 1,
  project_name: 'MRAG-Net',
  CUDA_VISIBLE_DEVICES: '0',  # 0, 1, 2, 3

  ### Train Parameters
  model_name: 'MRAGNet',
    n_classes: 1,
    in_channels: 3,
  dataloader: 'Image2Image_zero_pad',
  criterion: 'DiceBCELoss', # DiceBCELoss
  task: 'segmentation',
  input_space: 'RGB',
  input_channel: 3,
  input_size: [512, 512],
  optimizer: 'AdamW',
    lr: 0.001,
    scheduler: 'WarmupCosine',  # ConstantLRSchedule, WarmupCosine
    cycles: 100,
    warmup_epoch: 20,
    weight_decay: 0.05, # 0.05
  batch_size: 4,
  epoch: 10000,
  ema_decay: 0, # set 0 to deactivate
  class_weight: [1.0, 1.0],
  model_path: '', 
    freeze_layer: false,

  ### Augmentation Parameters
  transform_blur: true,
  transform_jitter: true,
  transform_hflip: true,
  transform_perspective: true,
  transform_cutmix: true,
  transform_rand_resize: true,
  transform_rand_crop: 288,

  train_x_path: 'data/DRIVE/train/input',
  train_y_path: 'data/DRIVE/train/label',
  val_x_path: 'data/DRIVE/val/input',
  val_y_path: 'data/DRIVE/val/label',
}
